// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.protocode;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseInfo = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string responseInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();

  /**
   * <code>int64 receiveTime = 2;</code>
   */
  long getReceiveTime();

  /**
   * <code>string UUID = 3;</code>
   */
  java.lang.String getUUID();
  /**
   * <code>string UUID = 3;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
