// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.protocode;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestInfo = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string requestInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();

  /**
   * <code>int64 requestTime = 2;</code>
   */
  long getRequestTime();

  /**
   * <code>string UUID = 3;</code>
   */
  java.lang.String getUUID();
  /**
   * <code>string UUID = 3;</code>
   */
  com.google.protobuf.ByteString
      getUUIDBytes();
}
