// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.jin.protocode;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jin.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.jin.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.jin.protocode.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.jin.proto.StudentResponse studentResponse = 1;</code>
   */
  com.jin.protocode.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.jin.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.jin.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.jin.protocode.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.jin.proto.StudentResponse studentResponse = 1;</code>
   */
  com.jin.protocode.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
